name: MGSkyWars
main: com.comze_instancelabs.mgskywars.Main
version: 1.3.0
author: InstanceLabs
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   sw:
      description: Main command
      usage: /sw [action]
      aliases: [skywars, mgskywars]
